version: '3.8'

services:
  # --- База данных ---
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Сервис Аутентификации  ---
  auth_service:
    build: ./backend/auth_service
    container_name: auth_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - api_network

  # --- Сервис Маркетплейса  ---
  marketplace_service:
    build: ./backend/marketplace_service
    container_name: marketplace_service
    env_file:
      - .env
    networks:
      - api_network

  # --- Nginx (Gateway) ---
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - auth_service
      - marketplace_service
    networks:
      - api_network

# --- ГЛОБАЛЬНАЯ СЕКЦИЯ СЕТЕЙ  ---
networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
